SoccerAnalyst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daily_odds/', include('daily_odds.urls')),
    path('ultra_odds/', include('ultra_odds.urls')),
    path('history/', include('history.urls')),
    path('weekly_run/', include('weekly_run.urls')),
]

history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('prev_daily/', views.PrevDailyView.as_view(), name='prev_daily'),
    path('prev_ultra/', views.PrevUltraView.as_view(), name='prev_ultra'),
    path('prev_weekly/', views.PrevWeeklyView.as_view(), name='prev_weekly'),

]

daily_odds/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class DailyMain(models.Model):
    slip_date = models.DateTimeField('slip_date', default=None)
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=40) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester





class DailySub(models.Model):
    daily_main = models.ForeignKey(DailyMain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

history/models.py
from django.db import models

# Create your models here.

ultra_odds/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class Ultramain(models.Model):
    slip_date = models.DateTimeField('slip_date')
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester


class Ultrasub(models.Model):
    ultra_main = models.ForeignKey(Ultramain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

weekly_run/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class Weeklymain(models.Model):
    slip_date = models.DateTimeField('slip_date')
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester


class Weeklysub(models.Model):
    weekly_main = models.ForeignKey(Weeklymain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

history/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from daily_odds.models import DailySub, DailyMain
from ultra_odds.models import Ultrasub, Ultramain
from weekly_run.models import Weeklysub, Weeklymain
from datetime import date, datetime


class PrevDailyView(generic.ListView):
    template_name = 'history/prev_daily.html'
    context_object_name = 'latest_prev_daily_list'

    def get_queryset(self):
        return DailyMain.objects.order_by('-slip_date')[:5]


class PrevUltraView(generic.ListView):
    template_name = 'history/prev_ultra.html'
    context_object_name = 'latest_prev_ultra_list'

    def get_queryset(self):
        return Ultramain.objects.order_by('-slip_date')[:5]


class PrevWeeklyView(generic.ListView):
    template_name = 'history/prev_weekly.html'
    context_object_name = 'latest_prev_weekly_list'

    def get_queryset(self):
        return Weeklymain.objects.order_by('-slip_date')[:5]

history/templates/history/prev_daily.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for dailymain in latest_prev_daily_list  %}
{% if dailymain.showing_prev %}

<h2>{{dailymain.slip_date}}</h2>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for dailysub in dailymain.dailysub_set.all %}



          {% if dailysub.outcome == null %}

              <tbody>

                 <tr>
                   <td>{{dailysub.match_date}}</td>
                   <td>{{dailysub.country}}</td>
                   <td>{{dailysub.home_team}}</td>
                   <td>{{dailysub.away_team}}</td>
                   <td>{{dailysub.prediction}}</td>
                   <td class= "p-2 mb-1 bg-warning text-dark">Running..</td>
                 </tr>
              </tbody>
          {% elif dailysub.outcome == dailysub.prediction %}
              <tbody>
                 <tr>
                   <td>{{dailysub.match_date}}</td>
                   <td>{{dailysub.country}}</td>
                   <td>{{dailysub.home_team}}</td>
                   <td>{{dailysub.away_team}}</td>
                   <td>{{dailysub.prediction}}</td>
                   <td class= "p-2 mb-1 bg-success text-white">{{dailysub.outcome}}</td>
                 </tr>
              </tbody>
          {% else %}


              <tbody>
                 <tr>
                   <td>{{dailysub.match_date}}</td>
                   <td>{{dailysub.country}}</td>
                   <td>{{dailysub.home_team}}</td>
                   <td>{{dailysub.away_team}}</td>
                   <td>{{dailysub.prediction}}</td>
                   <td class= "p-2 mb-1 bg-danger text-dark">{{dailysub.outcome}}</td>
                 </tr>
              </tbody>
          {% endif %}

      {% endfor %}

      </table>


 </ul>

{% endif %}
{% endfor %}

{% endblock %}
</html>

history/templates/history/prev_ultra.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for ultramain in latest_prev_ultra_list  %}
{% if ultramain.showing_prev %}
<h2>{{ultramain.slip_date}}</h2>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for ultrasub in ultramain.ultrasub_set.all %}



          {% if ultrasub.outcome == null %}

              <tbody>

                 <tr>
                   <td>{{ultrasub.match_date}}</td>
                   <td>{{ultrasub.country}}</td>
                   <td>{{ultrasub.home_team}}</td>
                   <td>{{ultrasub.away_team}}</td>
                   <td>{{ultrasub.prediction}}</td>
                   <td class="p-2 mb-1 bg-warning text-dark">Running..</td>
                 </tr>
              </tbody>

          {% elif ultrasub.outcome == ultrasub.prediction %}
               <tbody>
                 <tr>
                   <td>{{ultrasub.match_date}}</td>
                   <td>{{ultrasub.country}}</td>
                   <td>{{ultrasub.home_team}}</td>
                   <td>{{ultrasub.away_team}}</td>
                   <td>{{ultrasub.prediction}}</td>
                   <td class="p-2 mb-1 bg-success text-white">{{ultrasub.outcome}}</td>
                 </tr>
              </tbody>
          {% else %}


              <tbody>
                 <tr>
                   <td>{{ultrasub.match_date}}</td>
                   <td>{{ultrasub.country}}</td>
                   <td>{{ultrasub.home_team}}</td>
                   <td>{{ultrasub.away_team}}</td>
                   <td>{{ultrasub.prediction}}</td>
                   <td class="p-2 mb-1 bg-danger text-dark" >{{ultrasub.outcome}}</td>
                 </tr>
              </tbody>
          {% endif %}

      {% endfor %}

      </table>


 </ul>

{% endif %}
{% endfor %}
{% endblock %}
</html>

history/templates/history/prev_weekly.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for weeklymain in latest_prev_weekly_list  %}

<h2>{{weeklymain.slip_date}}</h2>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for weeklysub in weeklymain.weeklysub_set.all %}



          {% if weeklysub.outcome == null %}

              <tbody>

                 <tr>
                    <td>{{weeklysub.match_date}}</td>
                   <td>{{weeklysub.country}}</td>
                   <td>{{weeklysub.home_team}}</td>
                   <td>{{weeklysub.away_team}}</td>
                   <td>{{weeklysub.prediction}}</td>
                   <td class="p-2 mb-1 bg-warning text-dark">Running..</td>
                 </tr>
              </tbody>
          {% elif weeklysub.outcome == weeklysub.prediction %}
               <tbody>
                 <tr>
                   <td>{{weeklysub.match_date}}</td>
                   <td>{{weeklysub.country}}</td>
                   <td>{{weeklysub.home_team}}</td>
                   <td>{{weeklysub.away_team}}</td>
                   <td>{{weeklysub.prediction}}</td>
                   <td class="p-2 mb-1 bg-success text-white">{{weeklysub.outcome}}</td>
                 </tr>
              </tbody>
          {% else %}


              <tbody>
                 <tr>
                   <td>{{weeklysub.match_date}}</td>
                   <td>{{weeklysub.country}}</td>
                   <td>{{weeklysub.home_team}}</td>
                   <td>{{weeklysub.away_team}}</td>
                   <td>{{weeklysub.prediction}}</td>
                   <td class="p-2 mb-1 bg-danger text-dark">{{weeklysub.outcome}}</td>
                 </tr>
              </tbody>
          {% endif %}

      {% endfor %}

      </table>


 </ul>


{% endfor %}
{% endblock %}
</html>