SoccerAnalyst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daily_odds/', include('daily_odds.urls')),
    path('ultra_odds/', include('ultra_odds.urls')),
    path('history/', include('history.urls')),
    path('weekly_run/', include('weekly_run.urls')),
]

daily_odds/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'daily_odds'
urlpatterns = [
    # path('', views.index, name='index'),
    # url(r'^$', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DailydetView.as_view(), name='dailydet'),

]

history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('prev_daily/', views.PrevDailyView.as_view(), name='prev_daily'),
    path('prev_ultra/', views.PrevUltraView.as_view(), name='prev_ultra'),
    path('prev_weekly/', views.PrevWeeklyView.as_view(), name='prev_weekly'),

]

ultra_odds/urls.py
from django.urls import path
from . import views

app_name = 'ultra_odds'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('', views.UltraView.as_view(), name='ultra'),
    path('<int:pk>/', views.UltradetView.as_view(), name='ultradet'),

]

weekly_run/urls.py
from django.urls import path
from . import views

app_name = 'weekly_run'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('', views.WeeklyView.as_view(), name='weekly'),
    path('<int:pk>/', views.WeekdetView.as_view(), name='weekdet'),

]

daily_odds/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class DailyMain(models.Model):
    slip_date = models.DateTimeField('slip_date', default=None)
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=40) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester





class DailySub(models.Model):
    daily_main = models.ForeignKey(DailyMain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

daily_odds/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import DailyMain, DailySub


class IndexView(generic.ListView):
    template_name = 'daily_odds/index.html'
    context_object_name = 'latest_daily_list'

    def get_queryset(self):
        return DailyMain.objects.order_by('-slip_date')[:5]


class DailydetView(generic.DetailView):
    model = DailySub
    template_name = 'daily_odds/dailydet.html'

daily_odds/templates/daily_odds/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}  {% endblock title%}</title>
     <link rel="stylesheet" type="text/css" href="{% static 'daily_odds/css/mtx.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'daily_odds/css/bootstrap.min.css' %}" />

    <script src="{% static 'daily_odds/js/jquery3.3.1.js'%}"></script>


    <script src="{% static 'daily_odds/js/bootstrap.min.js'%}"></script>

</head>
<body>
 <div class="container-fluid">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="#">SoccerPedia</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
               aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                  <li class="nav-item active"><a class="nav-link" href="{% url 'daily_odds:index'%}">Home <span class="sr-only">
                      (current)</span> </a></li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle"  href="" id="navbarDropdown" role="button"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">prev</a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'history:prev_daily'%}"> daily tips</a>
                          <a class="dropdown-item" href="{% url 'history:prev_ultra'%}"> ultra</a>
                          <a class="dropdown-item" href="{% url 'history:prev_weekly'%}"> weekly</a>
                      </div>
                  </li>
                  <li class="nav-item" ><a class="nav-link" href="{% url 'ultra_odds:ultra' %}">ultra</a></li>
                  <li class="nav-item" ><a class="nav-link" href="{% url 'weekly_run:weekly' %}">week</a></li>
              </ul>
          </div>


  </nav>
 </div>
  <div id="page-header">
      {% block header %}{% endblock %}
  </div>

  <div id="content">
      {% block content %}


      {% endblock %}
  </div>

</body>
<footer>
<p > <center>&copy; 2018 Matrix Softwares Ltd. All rights reserved.</center></p>

</footer>
</html>

daily_odds/templates/daily_odds/dailydet.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}
<p>{{dailysub.country}} -- {{dailysub.prediction}}</p>


{% if dailysub %}

<table class="table table-striped ">
    <thead>
     <tr>
         <th>Stats</th>
         <th>{{dailysub.home_team}}</th>
         <th>Draw</th>
         <th>{{dailysub.away_team}}</th>
     </tr>
    </thead>
    <tbody>
     <tr>
         <td>H2H</td>
         <td>{{dailysub.h2h_home}}</td>
         <td>{{dailysub.h2h_draw}}</td>
         <td>{{dailysub.h2h_away}}</td>
     </tr>
    <tr>
         <td>Standings</td>
         <td>{{dailysub.standings_home}}</td>
         <td>-</td>
         <td>{{dailysub.standings_away}}</td>
     </tr>
    <tr>
         <td>Form</td>
         <td>{{dailysub.form_home}}</td>
         <td>-</td>
         <td>{{dailysub.form_away}}</td>
     </tr>
    <tr>
         <td>GS:GC</td>
         <td>{{dailysub.goals_home}}</td>
         <td>-</td>
         <td>{{dailysub.goals_away}}</td>
     </tr>
    <tr>
         <td>Missing Players</td>
         <td>{{dailysub.missing_players_home}}</td>
         <td>-</td>
         <td>{{dailysub.missing_players_away}}</td>
     </tr>

    </tbody>
</table>
{% endif%}

{% endblock %}
</html>

daily_odds/templates/daily_odds/index.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for dailymain in latest_daily_list  %}

 {% if dailymain.recent_slips %}

<h5 >{{dailymain.slip_date|date:'d/m/Y'}}</h5>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for dailysub in dailymain.dailysub_set.all %}



          {% if dailysub.outcome == null %}

              <tbody>

                 <tr>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.match_date|date:'d/m/Y'}} -{{dailysub.match_date|time:'H:i'}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.prediction}}</a></td>
                   <td><a class= "p-2 mb-1 bg-warning text-dark" href="{% url 'daily_odds:dailydet' dailysub.id %}">Running..</a></td>
                 </tr>
              </tbody>
          {% elif dailysub.outcome == dailysub.prediction %}


              <tbody >

                 <tr>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.match_date|date:'d/m/Y'}} -{{dailysub.match_date|time:'H:i'}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.prediction}}</a></td>
                   <td><a class= "p-2 mb-1 bg-success text-white" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.outcome}}</a></td>
                 </tr>

              </tbody>

          {% else %}

              <tbody>
                 <tr>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.match_date|date:'d/m/Y'}} -{{dailysub.match_date|time:'H:i'}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.prediction}}</a></td>
                   <td><a class= "p-2 mb-1 bg-danger text-dark" href="{% url 'daily_odds:dailydet' dailysub.id %}">{{dailysub.outcome}}</a></td>
                 </tr>
              </tbody>

          {% endif %}

      {% endfor %}

      </table>


 </ul>

 {% endif %}
{% endfor %}
{% endblock %}
</html>