SoccerAnalyst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daily_odds/', include('daily_odds.urls')),
    path('ultra_odds/', include('ultra_odds.urls')),
    path('history/', include('history.urls')),
    path('weekly_run/', include('weekly_run.urls')),
]

history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('prev_daily/', views.PrevDailyView.as_view(), name='prev_daily'),
    path('prev_ultra/', views.PrevUltraView.as_view(), name='prev_ultra'),
    path('prev_weekly/', views.PrevWeeklyView.as_view(), name='prev_weekly'),

]

weekly_run/urls.py
from django.urls import path
from . import views

app_name = 'weekly_run'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('', views.WeeklyView.as_view(), name='weekly'),
    path('<int:pk>/', views.WeekdetView.as_view(), name='weekdet'),

]

weekly_run/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class Weeklymain(models.Model):
    slip_date = models.DateTimeField('slip_date')
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester


class Weeklysub(models.Model):
    weekly_main = models.ForeignKey(Weeklymain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

weekly_run/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Weeklymain, Weeklysub


class WeeklyView(generic.ListView):
    template_name = 'weekly_run/weekly.html'
    context_object_name = 'latest_weekly_list'

    def get_queryset(self):
        return Weeklymain.objects.order_by('-slip_date')[:5]


class WeekdetView(generic.DetailView):
    model = Weeklysub
    template_name = 'weekly_run/weekdet.html'

weekly_run/templates/weekly_run/weekdet.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}
<p>{{weeklysub.country}} -- {{weeklysub.prediction}}</p>


{% if weeklysub %}

<table class="table table-striped ">
    <thead>
     <tr>
         <th>Stats</th>
         <th>{{weeklysub.home_team}}</th>
         <th>Draw</th>
         <th>{{weeklysub.away_team}}</th>
     </tr>
    </thead>
    <tbody>
     <tr>
         <td>H2H</td>
         <td>{{weeklysub.h2h_home}}</td>
         <td>{{weeklysub.h2h_draw}}</td>
         <td>{{weeklysub.h2h_away}}</td>
     </tr>
    <tr>
         <td>Standings</td>
         <td>{{weeklysub.standings_home}}</td>
         <td>-</td>
         <td>{{weeklysub.standings_away}}</td>
     </tr>
    <tr>
         <td>Form</td>
         <td>{{weeklysub.form_home}}</td>
         <td>-</td>
         <td>{{weeklysub.form_away}}</td>
     </tr>
    <tr>
         <td>GS:GC</td>
         <td>{{weeklysub.goals_home}}</td>
         <td>-</td>
         <td>{{weeklysub.goals_away}}</td>
     </tr>
    <tr>
         <td>Missing Players</td>
         <td>{{weeklysub.missing_players_home}}</td>
         <td>-</td>
         <td>{{weeklysub.missing_players_away}}</td>
     </tr>

    </tbody>
</table>
{% endif%}

{% endblock %}
</html>

weekly_run/templates/weekly_run/weekly.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for weeklymain in latest_weekly_list  %}

<h2>{{weeklymain.slip_date}}</h2>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for weeklysub in weeklymain.weeklysub_set.all %}



          {% if weeklysub.outcome == null %}

              <tbody>

                 <tr>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-warning text-dark" href="{% url 'weekly_run:weekdet' weeklysub.id %}">Running..</a></td>
                 </tr>
              </tbody>
          {% elif weeklysub.outcome == weeklysub.prediction %}
              <tbody>
                 <tr>

                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-success text-white" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.outcome}}</a></td>
                 </tr>
              </tbody>
          {% else %}


              <tbody>
                 <tr>

                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-danger text-dark"  href="{% url 'weekly_run:weekdet' weeklysub.id %}">{{weeklysub.outcome}}</a></td>
                 </tr>
              </tbody>
          {% endif %}

      {% endfor %}

      </table>


 </ul>


{% endfor %}
{% endblock %}
</html>