SoccerAnalyst/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('daily_odds/', include('daily_odds.urls')),
    path('ultra_odds/', include('ultra_odds.urls')),
    path('history/', include('history.urls')),
    path('weekly_run/', include('weekly_run.urls')),
]

history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('prev_daily/', views.PrevDailyView.as_view(), name='prev_daily'),
    path('prev_ultra/', views.PrevUltraView.as_view(), name='prev_ultra'),
    path('prev_weekly/', views.PrevWeeklyView.as_view(), name='prev_weekly'),

]

ultra_odds/urls.py
from django.urls import path
from . import views

app_name = 'ultra_odds'
urlpatterns = [

    # url(r'^$', views.index, name='index'),
    path('', views.UltraView.as_view(), name='ultra'),
    path('<int:pk>/', views.UltradetView.as_view(), name='ultradet'),

]

ultra_odds/models.py
from django.db import models
import datetime

from django.db import models
from django.utils import timezone


class Ultramain(models.Model):
    slip_date = models.DateTimeField('slip_date')
    slip_name = models.CharField(max_length=40, null=True, blank=True)

    def name(self):
        return self.outcome

    def recent_slips(self):
        now = timezone.now()
        return now - datetime.timedelta(days=4) <= self.slip_date <= now

    def showing_prev(self):
        now = timezone.now()
        yester = now - datetime.timedelta(1)
        return now - datetime.timedelta(days=40) <= self.slip_date <= yester


class Ultrasub(models.Model):
    ultra_main = models.ForeignKey(Ultramain, on_delete=models.CASCADE, default=None)
    country = models.CharField(max_length=30, default=None)
    home_team = models.CharField(max_length=30)
    away_team = models.CharField(max_length=30)
    prediction = models.CharField(max_length=40)
    outcome = models.CharField(max_length=20, null=True, blank=True)
    match_date = models.DateTimeField('match date')
    h2h_home = models.CharField(max_length=30, default=None)
    h2h_away = models.CharField(max_length=30, default=None)
    h2h_draw = models.CharField(max_length=30, default=None)
    standings_home = models.CharField(max_length=30, default=None)
    standings_away = models.CharField(max_length=30, default=None)
    form_home = models.CharField(max_length=30, default=None)
    form_away = models.CharField(max_length=30, default=None)
    goals_home = models.IntegerField(default=None)
    goals_away = models.IntegerField(default=None)
    missing_players_home = models.CharField(max_length=300, default=None)
    missing_players_away = models.CharField(max_length=300, default=None)

    def __str__(self):
        return self.home_team

    def __str__(self):
        return self.away_team

    def __str__(self):
        return self.prediction

    def match_outcome(self):
        return self.outcome

    def recent_matches(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.match_date <= now

ultra_odds/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Ultramain, Ultrasub


class UltraView(generic.ListView):
    template_name = 'ultra_odds/ultra.html'
    context_object_name = 'latest_ultra_list'

    def get_queryset(self):
        return Ultramain.objects.order_by('-slip_date')[:5]


class UltradetView(generic.DetailView):
    model = Ultrasub
    template_name = 'ultra_odds/ultradet.html'

ultra_odds/templates/ultra_odds/ultra.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block title %} Soccer {% endblock title%}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}

{% for ultramain in latest_ultra_list  %}
  {% if ultramain.recent_slips %}


<h2>{{ultramain.slip_date}}</h2>
<ul>


      <table class="table table-striped ">

          <thead class="thead-dark ">
                 <tr>
                     <th scope="col">Date</th>
                     <th scope="col">country</th>
                     <th scope="col">home team</th>
                     <th scope="col">away team</th>
                     <th scope="col">prediction</th>
                     <th scope="col">outcome</th>

                 </tr>

          </thead>


      {% for ultrasub in ultramain.ultrasub_set.all %}



          {% if ultrasub.outcome == null %}

              <tbody class="{% cycle 'odd' 'even' %}">

                 <tr>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-warning text-dark" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">Running...</a></td>
                 </tr>
              </tbody>

          {% elif ultrasub.outcome == ultrasub.prediction %}
               <tbody class="{% cycle 'odd' 'even' %}">
                 <tr>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-success text-white" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.outcome}}</a></td>
                 </tr>
              </tbody>
          {% else %}


              <tbody class="{% cycle 'odd' 'even' %}">
                 <tr>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.match_date}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.country}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.home_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.away_team}}</a></td>
                   <td><a class="nav-link" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.prediction}}</a></td>
                   <td><a class="p-2 mb-1 bg-danger text-dark" href="{% url 'ultra_odds:ultradet' ultrasub.id %}">{{ultrasub.outcome}}</a></td>
                 </tr>
              </tbody>
          {% endif %}

      {% endfor %}
      {% resetcycle %}

      </table>


 </ul>

 {% endif %}
{% endfor %}
{% endblock %}
</html>

ultra_odds/templates/ultra_odds/ultradet.html
<!DOCTYPE html>
<html>
{% extends "daily_odds/base.html" %}
{% load static %}
{% block header %} <h4> Tips</h4> {% endblock %}

{% block content %}
<p>{{ultrasub.country}} -- {{ultrasub.prediction}}</p>


{% if ultrasub %}

<table class="table table-striped ">
    <thead>
     <tr>
         <th>Stats</th>
         <th>{{ultrasub.home_team}}</th>
         <th>Draw</th>
         <th>{{ultrasub.away_team}}</th>
     </tr>
    </thead>
    <tbody>
     <tr>
         <td>H2H</td>
         <td>{{ultrasub.h2h_home}}</td>
         <td>{{ultrasub.h2h_draw}}</td>
         <td>{{ultrasub.h2h_away}}</td>
     </tr>
    <tr>
         <td>Standings</td>
         <td>{{ultrasub.standings_home}}</td>
         <td>-</td>
         <td>{{ultrasub.standings_away}}</td>
     </tr>
    <tr>
         <td>Form</td>
         <td>{{ultrasub.form_home}}</td>
         <td>-</td>
         <td>{{ultrasub.form_away}}</td>
     </tr>
    <tr>
         <td>GS:GC</td>
         <td>{{ultrasub.goals_home}}</td>
         <td>-</td>
         <td>{{ultrasub.goals_away}}</td>
     </tr>
    <tr>
         <td>Missing Players</td>
         <td>{{ultrasub.missing_players_home}}</td>
         <td>-</td>
         <td>{{ultrasub.missing_players_away}}</td>
     </tr>

    </tbody>
</table>
{% endif%}

{% endblock %}
</html>